
source 'http://code.dapps.douban.com/CocoaPodsSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'REFrostedViewController',                    '~> 2.4.5'
pod 'CHTCollectionViewWaterfallLayout',           '~> 0.6'
pod 'AFNetworking',                               '~> 2.2.3'
pod 'JSONModel',                                  '~> 0.13.0'
pod 'AMWaveTransition',                           '~> 0.3'
pod 'MRProgress',                                 '~> 0.4.3'
pod 'SVPullToRefresh',                            '~> 0.4.1'
pod 'MWPhotoBrowser',                             '~> 1.4.1'
pod 'SDWebImage',                                 '~> 3.7.1'
pod 'RMDateSelectionViewController',              '~> 1.2.1'
pod 'MBProgressHUD',                              '~> 0.8'
pod 'GPUImage',                                   '~> 0.1.5'
pod 'FXBlurView',                                 '~> 1.6.1'
pod 'APNumberPad',                                '~> 1.0'
pod 'PSAlertView',                                '~> 2.0.2'
pod 'UICountingLabel',                            '~> 1.1.0'
pod 'PureLayout',                                 '~> 2.0.1'
pod 'ADTransitionController',                     '~> 1.1.1'
pod 'libextobjc',                                 '~> 0.4.1'