platform :ios, '7.0'

pod 'REFrostedViewController',                    '~> 2.4.5'
pod 'CHTCollectionViewWaterfallLayout',           '~> 0.6'
pod 'AFNetworking',                               '~> 2.2.3'
pod 'UIView+AutoLayout',                          '~> 1.3.0'
pod 'JSONModel',                                  '~> 0.13.0'
pod 'AMWaveTransition',                           '~> 0.3'
pod 'MRProgress',                                 '~> 0.4.3'
pod 'SVPullToRefresh',                            '~> 0.4.1'
pod 'MWPhotoBrowser',                             '~> 1.4.0'
pod 'SDWebImage',                                 '~> 3.5.4'
pod 'RMDateSelectionViewController',              '~> 1.2.1'
pod 'MBProgressHUD',                              '~> 0.8'
pod 'GPUImage',                                   '~> 0.1.4'
pod 'FXBlurView',                                 '~> 1.6.1'